### ISSUE TITLE
transaction callbacks are never called [in case of invalid db handle]

### ISSUE THREAD

**Issue by sikron** [brodysoft/Cordova-sqlcipher-adaptor#1]
Hi,
i just exchanged the SQLitePlugin (1.0.6) with the SQLCipher-Adaptor in my project via "cordova plugin add ...". Then i added the "key-parameter to the openDatabase(). Now neither the success- nor the error-callback of the transaction are called. Has something changed here?

My code:
var db = window.sqlitePlugin.openDatabase({name: "mydb", key: "your-password-here"});
db.transaction(create, error, success);

with create, error and success being proper functions.

Thank you!

**Comment by brodybits** [comment]
I suspect that you are trying to open an unencrypted database with a password key. The `db.transaction()` call is expecting the db to become valid, but this is not the case. As a workaround, simply remove your app from your emulator or device and try it again. Another suggestion is to wait for the `sqlitePlugin.openDatabase()` success callback before attempting any transaction(s).

**Comment by brodybits** [comment]
@sikron can you report whether you saw this on the Android or iOS platform (or both)?

**Comment by brodybits** [comment]
REPRODUCTION:

The following test succeeds on the iOS version but fails with a timeout on the Android version:

```Javascript
        if (!isWebSql) test(suiteName + 'Attempt to open and read unencrypted DB with password key', function () {

          var dbName = 'Open-and-read-unencrypted-DB-with-password.db';

          stop(2);
        
          openDatabase({name: dbName}, function (db) {
            ok(!!db, 'valid db object');
            db.transaction(function(tx) {
              tx.executeSql('DROP TABLE IF EXISTS tt');
              tx.executeSql('CREATE TABLE IF NOT EXISTS tt (test_data)');
              tx.executeSql('INSERT INTO tt (test_data) VALUES (?)', ['test data']);
            }, function(error) {
              console.log('ERROR: ' + error.message);
              ok(false, error.message);
              start(2);
            }, function() {
              db.close(function () {
                ok(true, 'Ready to open unencrypted db with password key');
                start(1);

                var db1 = openDatabase({name: dbName, key: 'test-password'});
                db1.transaction(function(tx) {
                  tx.executeSql('SELECT * FROM tt');
                }, function(error) {
                  console.log('ERROR: ' + error.message);
                  ok(true, 'Attempted transaction on invalid db should fail');
                  start(1);
                }, function() {
                  ok(false, 'Attempted transaction on invalid db should not succeed');
                  start(1);
                });
              }, function (error) {
                ok(false, error.message);
                start(2);
              });
            });
          }, function (error) {
            ok(false, error.message);
            start(2);
          });
        });
```

**Comment by sikron** [comment]
Hi,
i have a Samsung Galaxy S2 with Cyanogenmod 11 (Android 4.4.4). And your explanation was totally right, i already had a unencrypted database on the device. I uninstalled the app completely, re-installed it (which created a new encrypted database) and now it runs as before so far.
Thank you very much!

**Comment by brodybits** [comment]
Happy to hear @sikron. This bug report actually helped me improve a case of error handling so thanks to you too!
