### ISSUE TITLE
Select query in iOS returning value with .0 appended to it for integer values after using wk-webview-engine

### ISSUE THREAD

**Issue by shaik-azmat** [brodysoft/Cordova-sqlcipher-adaptor#100]
Hi,
 I am using  following plugins:
**cordova-sqlcipher-adapter 0.2.0
cordova-plugin-wkwebview-engine 1.2.1
cordova-plugin-wkwebviewxhrfix 0.1.0**

Whenever a select query is executed and data is retreived from sqlite db, if any of the columns has integer value, .0 is appending to it even though during inserting only integer value is given. Please suggest me a solution for this 

For example **1** is retrieved as **1.0**

**Comment by brody2consult** [comment]
My apologies for the delay. You seem to have a really old version of this plugin which is generally not supported. I would highly recommend that you upgrade to the latest version. I would also recommend you consider upgrading to cordova-ios@6, which has switched to WKWebView, get rid of wkwebview-engine, and maybe get rid of wkwebviewxhrfix plugin.

I do recall seeing this kind of thing happen with WKWebView, will investigate.

**Comment by shaik-azmat** [comment]
After upgrading to cordova-ios@6.0.0. Getting following issue while running the app in xcode 11.4

No known instance method for selector 'userAgent' in CDVFileTransfer.m

**Comment by brody2consult** [comment]
The Cordova file transfer plugin is now deprecated.

I would recommend that you try using cordova-ios@5.1.1 (previous release) and latest update of all other plugins including this one.

I took another look at the test suite. From what I see, it would only append ".0" if you store an integer value in a TEXT column. I would recommend using INTEGER column type to store an integer value. And I do not see this issue in case of a NUMERIC column, REAL column, or a column with no type affinity.

I did just run the test suite with cordova-ios@5 (cordova-ios@5.1.1) and cordova-plugin-wkwebview-engine@latest (cordova-plugin-wkwebview-engine@1.2.1) to be absolutely sure.

I don't k

**Comment by brody2consult** [comment]
Sorry for accidental closing. I hope this helps.

**Comment by ashishkumar2804** [comment]
@brodybits I tried upgrading my app to latest cordova ios version and there seems to be some issue with the plugin. window.SqlitePlugin is undefined is thrown.

the plugin works perfectly fine with cordova ios 5.11. Please let me know, how to get this fixed.

**Comment by brody2consult** [comment]
I think we can close this issue since you raised #101 with your upgrade issue.
