### ISSUE TITLE
Incorrect blob storage

### ISSUE THREAD

**Issue by ishigo1987** [brodysoft/Cordova-sqlcipher-adaptor#102]
I create a field with BLOB data type and i store a javascript blob inside it, but when i retrieve the contain of this field i've a string
[object Blob]
Is it normal?

Android 8
Cordova 9

**Comment by ishigo1987** [comment]
"CREATE TABLE IF NOT EXISTS contacts (_id INTEGER PRIMARY KEY, username VARCHAR(255), local_thumbnail_profile_picture BLOB)"

Example

**Comment by brody2consult** [comment]
BLOB data storage is not supported by this plugin version.

BASE64 function is supported by <https://github.com/brodybits/cordova-sqlite-ext>, and it would be possible to add to this plugin version if there is sufficient interest from the user community.

Priority goes to commercial users, please contact <sales@xpbrew.consulting> in case of interest.

**Comment by ishigo1987** [comment]
ok got it
