### ISSUE TITLE
executesql promise not transaction

### ISSUE THREAD

**Issue by medida** [brodysoft/Cordova-sqlcipher-adaptor#111]
Hello, 

This is a simple question - but one i have not managed to find an answer to...

So I have swapped over from the standard sqlite plugin to the sqlcipher one - which is supposed ot be a direct replacement.

However i've been using the old plugin as such
` this._database.executeSql(sqlCommand, []).then(data => {
            //  console.log(data);
          }));`

But sqlcipher does not have a promise from the executesql ... Is there away to make it like this so i don't need to edit an entire project.

Is there a wrapper which i could use or am I going to have to edit all my code.

Thanks

**Comment by brody2consult** [comment]
Maybe this can help: https://github.com/brodybits/sql-promise-helper
