### ISSUE TITLE
Trying to remove any _other_ plugin results in an error when this plugin is installed

### ISSUE THREAD

**Issue by chrisweight** [brodysoft/Cordova-sqlcipher-adaptor#73]
When trying to run a `cordova plugin remove cordova-plugin-*` with this plugin installed, this consistently returns:

```
Uninstalling cordova-plugin-* from android
Subproject Path: CordovaLib
Removing "cordova-plugin-*"
Error: Cannot find plugin.xml for plugin "cordova-sqlite-storage". Please try adding it again.
[ERROR] An error occurred while running subprocess cordova.

        cordova plugin remove cordova-plugin-* --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

This is with `cordova-android@6.4.0`, cordova cli @ 7.1.0

I have tried this with a number of different plugins, with the same result

**Comment by chrisweight** [comment]
Morning! Any thoughts on this? Do you need more detail from me?

**Comment by brody2consult** [comment]
A demo project would be helpful.

It looks like you are using old Cordova version, which I generally do not
test on any more.

I would upgrade to the latest version of Cordova then add all plugins and
platforms from scratch.

I hope you are not keeping the plugins and platforms in a repository.

**Comment by chrisweight** [comment]
no, not keeping those in a repo!

We have over 30 plugins in use in this project. I will try and find time to do that. Wish me luck!

**Comment by chrisweight** [comment]
That _seems_ to have sorted it, will close this and re-visit if needed
