### ISSUE TITLE
Windows fallback using cordova-sqlite-storage

### ISSUE THREAD

**Issue by nsteenbeek** [brodysoft/Cordova-sqlcipher-adaptor#78]
Since 0.1.12 the Windows app has no window.sqlitePlugin anymore to support opening a db without 'key' option. Using cordova-sqlite-storage is not an option, since that will brake Android/iOS, because it uses window.sqlitePlugin too. How to get Windows running in same codebase?

**Comment by brody2consult** [comment]
I would use a conditional based on whether or not your app is on windows. If you app is on Windows then you would open the database with no key option. I hope this helps.

**Comment by nsteenbeek** [comment]
I tried that, but then found window.sqlitePlugin was not there. That due to plugin.xml

    <platform name="windows-disabled">

That results in no sqlitePlugin at all for Windows.

**Comment by brody2consult** [comment]
My apologies for the delay, you are correct. Windows support is dropped for now, as discussed in #63. I will explain further in #63, closing this one as a duplicate.
