### ISSUE TITLE
SQLite 3.26.0 security update

### ISSUE THREAD

**Issue by brody2consult** [brodysoft/Cordova-sqlcipher-adaptor#79]
SQLite 3.26.0 update is needed due to a known vulnerability, as discussed in:
* litehelpers/Cordova-sqlite-storage#837
* <https://discuss.zetetic.net/t/magellan-vulnerbility/3290>

It should be possible to apply this patch to SQLCipher as described in <https://discuss.zetetic.net/t/sqlcipher-sqlite-update/2470>.

I would like to do this before the SQLCipher 4 update, which has breaking changes.

**Comment by kohlia** [comment]
How will this affect the current usage, also when can we expect the changes

**Comment by brody2consult** [comment]
> How will this affect the current usage

Should be the same as upgrading from an older version of SQLite to SQLite 3.26.0. The window functions feature should be available but I am not sure when I will explicitly test it.

> when can we expect the changes

Hopefully within the next 1-2 weeks, in parallel to some other commitments.

In case anyone would like to purchase priority update support please contact <sales@litehelpers.net>.

**Comment by brody2consult** [comment]
I published version `0.1.12-rc3` which has FTS3 and FTS5 security updates from SQLite 3.26.0.

Full SQLite 3.26.0 security update will come with SQLCipher 4.0.1 update (#80).
