### ISSUE TITLE
Android: Database is opening with any key

### ISSUE THREAD

**Issue by bastifix** [brodysoft/Cordova-sqlcipher-adaptor#93]
Hi, I use the plugin for about a year now and it worked perfect. Unfortunately it stopped somehow working on android and the curious thing is that the db opens with any key. On iOS it's fine. 
It's hard for me to tell where the problem comes from, because the only versions which where running together for me where cordova-sqlite-storage@2.4.0 and cordova-sqlcipher-adapter@0.1.12-rc3. As said it worked quite well and stopped on android now. Updating to higher versions are ending up in different errors.
Is there an explanation for the opening behaviour? 

Thanks in advance!

**Comment by brody2consult** [comment]
Please be sure to remove cordova-sqlite-storage and any other variant of SQLite plugin or library. Using multiple SQLite plugins including this one leads to undefined behavior. I have already documented this, evidently not clearly enough.

I would also highly recommend that you upgrade to the latest version possible. Older versions should not be considered secure.

**Comment by bastifix** [comment]
Oh no, sorry for my stupidity!
I read this but there also were errors, a simple
`cordova clean`
did then the trick. 

Thanks for your time and this awesome plugin!
